name: JS Action Demo
description: "js action demo"

inputs:
  username:
    description: Username
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: npm --prefix ${{ github.action_path }} install

    - name: Run JS Action
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js