name: conditional workflow
on: 
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on : ubuntu-latest
    steps:
      - name : print message
        if: github.repository == "Jitendra-2848/CI-CD_Demo"
        run: echo "Condition is true"
      - name : print 
        if: github.repository != "Jitendra-2848/CI-CD_Demo"
        run: echo "condition is false"