name: Workflow-command for set environment variable
on:
  push:
    branches:
      - main
jobs:
  producer:
    runs-on: ubuntu-latest
    outputs:
      Dog: ${{ steps.set-environment.outputs.Dog }}
      Cat: ${{ steps.set-environment.outputs.Cat }}
    steps:
      - name: setting-environment
        id: set-environment
        run: |
          name="Jitendra"
          echo "Dog=Woof" >> "$GITHUB_OUTPUT"
          echo "Cat=Meow" >> "$GITHUB_OUTPUT"
          echo "Ronaldo=Sui" >> "$GITHUB_ENV"
          echo "name=$name" >> "$GITHUB_ENV"
      - name: print-environment
        run: |
          echo "${{ steps.set-environment.outputs.Dog }}"
          echo "${{ steps.set-environment.outputs.Cat }}"
          echo "${Ronaldo}"
          echo "${name}"

  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - name: get environment variable
        run: |
          echo "${{ needs.producer.outputs.Dog}}"
          echo "${{ needs.producer.outputs.Cat}}"
