name: secret and environment

on: workflow_dispatch

jobs:
  local-staging:
    runs-on: ubuntu-latest
    environment: staging

    env:
      DOG: ${{ secrets.DOG }}
      CAT: ${{ vars.CAT }}
      TOKEN: ${{ secrets.TOKEN }}
      GOAT: ${{ vars.GOAT }}

    steps:
      - name: print staging values
        run: |
          echo "Dog: $DOG"
          echo "Cat: $CAT"
          echo "Token: $TOKEN"
          echo "Goat: $GOAT"

  production:
    needs: local-staging
    runs-on: ubuntu-latest
    environment: production

    env:
      DOG: ${{ secrets.DOG }}
      CAT: ${{ vars.CAT }}
      TOKEN: ${{ secrets.TOKEN }}
      GOAT: ${{ vars.GOAT }}

    steps:
      - name: print production values
        run: |
          echo "Dog: $DOG"
          echo "Cat: $CAT"
          echo "Token: $TOKEN"
          echo "Goat: $GOAT"